<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-05T06:27:45Z" name="Suite" finished-at="2023-08-05T06:36:11Z" duration-ms="505763">
    <groups>
      <group name="Purchase">
        <method signature="StandAloneTest2.submitOrder(java.util.HashMap)[pri:0, instance:com.workpulse.test.StandAloneTest2@5d5f10b2]" name="submitOrder" class="com.workpulse.test.StandAloneTest2"/>
      </group> <!-- Purchase -->
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.loginErrorValidation()[pri:0, instance:com.workpulse.test.ErrorValidationTest@366ac49b]" name="loginErrorValidation" class="com.workpulse.test.ErrorValidationTest"/>
        <method signature="ErrorValidationTest.productErrorValidation()[pri:0, instance:com.workpulse.test.ErrorValidationTest@366ac49b]" name="productErrorValidation" class="com.workpulse.test.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2023-08-05T06:27:45Z" name="Submit the Order" finished-at="2023-08-05T06:32:52Z" duration-ms="306499">
      <class name="com.workpulse.test.StandAloneTest2">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.workpulse.test.StandAloneTest2@5d5f10b2]" started-at="2023-08-05T06:27:46Z" name="launchApplication" finished-at="2023-08-05T06:29:18Z" duration-ms="91888" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:com.workpulse.test.StandAloneTest2@5d5f10b2]" started-at="2023-08-05T06:29:18Z" name="submitOrder" data-provider="getData" finished-at="2023-08-05T06:29:32Z" duration-ms="14660" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Artis!@#123, countryName=india, email=rohankg09@gmail.com, productName=ZARA COAT 3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.workpulse.test.StandAloneTest2@5d5f10b2]" started-at="2023-08-05T06:29:32Z" name="tearDown" finished-at="2023-08-05T06:29:33Z" duration-ms="234" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.workpulse.test.StandAloneTest2@5d5f10b2]" started-at="2023-08-05T06:29:33Z" name="launchApplication" finished-at="2023-08-05T06:31:07Z" duration-ms="94193" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:com.workpulse.test.StandAloneTest2@5d5f10b2]" started-at="2023-08-05T06:31:07Z" name="submitOrder" data-provider="getData" finished-at="2023-08-05T06:31:22Z" duration-ms="14831" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Artis!@#123, countryName=india, email=rohankg09@gmail.com, productName=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.workpulse.test.StandAloneTest2@5d5f10b2]" started-at="2023-08-05T06:31:22Z" name="tearDown" finished-at="2023-08-05T06:31:22Z" duration-ms="307" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.workpulse.test.StandAloneTest2@5d5f10b2]" started-at="2023-08-05T06:31:22Z" name="launchApplication" finished-at="2023-08-05T06:32:51Z" duration-ms="89141" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="orderHistoryTest()[pri:0, instance:com.workpulse.test.StandAloneTest2@5d5f10b2]" started-at="2023-08-05T06:32:51Z" name="orderHistoryTest" finished-at="2023-08-05T06:32:52Z" depends-on-methods="com.workpulse.test.StandAloneTest2.submitOrder" duration-ms="825" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.workpulse.test.StandAloneTest2@5d5f10b2]" started-at="2023-08-05T06:32:52Z" name="tearDown" finished-at="2023-08-05T06:32:52Z" duration-ms="175" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.workpulse.test.StandAloneTest2 -->
    </test> <!-- Submit the Order -->
    <test started-at="2023-08-05T06:32:52Z" name="Validate the Error Handeling" finished-at="2023-08-05T06:36:11Z" duration-ms="198897">
      <class name="com.workpulse.test.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.workpulse.test.ErrorValidationTest@366ac49b]" started-at="2023-08-05T06:32:52Z" name="launchApplication" finished-at="2023-08-05T06:34:22Z" duration-ms="89725" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:com.workpulse.test.ErrorValidationTest@366ac49b]" started-at="2023-08-05T06:34:22Z" name="loginErrorValidation" finished-at="2023-08-05T06:34:23Z" duration-ms="902" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email  password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email  password.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.workpulse.test.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.workpulse.test.ErrorValidationTest@366ac49b]" started-at="2023-08-05T06:34:23Z" name="tearDown" finished-at="2023-08-05T06:34:24Z" duration-ms="257" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.workpulse.test.ErrorValidationTest@366ac49b]" started-at="2023-08-05T06:34:24Z" name="launchApplication" finished-at="2023-08-05T06:35:57Z" duration-ms="93069" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:com.workpulse.test.ErrorValidationTest@366ac49b]" started-at="2023-08-05T06:35:57Z" name="productErrorValidation" finished-at="2023-08-05T06:36:11Z" duration-ms="14194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.workpulse.test.ErrorValidationTest@366ac49b]" started-at="2023-08-05T06:36:11Z" name="tearDown" finished-at="2023-08-05T06:36:11Z" duration-ms="237" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.workpulse.test.ErrorValidationTest -->
    </test> <!-- Validate the Error Handeling -->
  </suite> <!-- Suite -->
</testng-results>
